//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDiagram")]

namespace UPM_IPS.RDMDCM_ProyectoIPS
{
	/// <summary>
	/// DomainClass RDMDCM_ProyectoIPSDiagram
	/// Description for UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel), "UPM_IPS.RDMDCM_ProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDiagram.Description", typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel), "UPM_IPS.RDMDCM_ProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("c75f8b19-d391-4ed0-8584-a14b0b65762f")]
	public partial class RDMDCM_ProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Diagram styles
		/// <summary>
		/// Initializes style set resources for this shape type
		/// </summary>
		/// <param name="classStyleSet">The style set for this shape class</param>
		protected override void InitializeResources(DslDiagrams::StyleSet classStyleSet)
		{
			base.InitializeResources(classStyleSet);
			
			// Fill brush settings for this shape.
			DslDiagrams::BrushSettings backgroundBrush = new DslDiagrams::BrushSettings();
			backgroundBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.Gray);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, backgroundBrush);
		
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaPrincipal)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaPrincipal newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaPrincipal(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaSecundaria)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaSecundaria newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaSecundaria(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.Menu)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaMenu newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaMenu(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenu)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaItemMenu newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaItemMenu(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.Boton)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaBoton newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaBoton(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaEstadoFin newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaEstadoFin(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenuReferencesVentana)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionAccion newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionAccion(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.BotonReferencesVentana)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionAccion newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionAccion(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.BotonReferencesEstadoFin)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionFin newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionFin(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenuReferencesEstadoFin)
			{
				global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionFin newShape = new global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaRelacionFin(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaPrincipal.DecoratorsInitialized += MetaforaVentanaPrincipalDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaSecundaria.DecoratorsInitialized += MetaforaVentanaSecundariaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaMenu.DecoratorsInitialized += MetaforaMenuDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaItemMenu.DecoratorsInitialized += MetaforaItemMenuDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaBoton.DecoratorsInitialized += MetaforaBotonDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaEstadoFin.DecoratorsInitialized += MetaforaEstadoFinDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaVentanaPrincipal.
		/// </summary>
		internal static partial class MetaforaVentanaPrincipalDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaVentanaPrincipal.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreVentana").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.anchoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ancho").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.altoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaVentanaSecundaria.
		/// </summary>
		internal static partial class MetaforaVentanaSecundariaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaVentanaSecundaria.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreVentana2").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaSecundaria.modalDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "modal").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.anchoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ancho2").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.altoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alto2").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaMenu.
		/// </summary>
		internal static partial class MetaforaMenuDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaMenu.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Menu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreMenu").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaItemMenu.
		/// </summary>
		internal static partial class MetaforaItemMenuDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaItemMenu.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreItem").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaBoton.
		/// </summary>
		internal static partial class MetaforaBotonDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaBoton.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.Boton.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEstadoFin.
		/// </summary>
		internal static partial class MetaforaEstadoFinDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEstadoFin.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.RDMDCM_ProyectoIPS.RelacionAccionConnectAction relacionAccionConnectAction;
		private global::UPM_IPS.RDMDCM_ProyectoIPS.RelacionFinConnectAction relacionFinConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSToolboxHelper.RelacionAccionFilterString))
				{
					if (this.relacionAccionConnectAction == null)
					{
						this.relacionAccionConnectAction = new global::UPM_IPS.RDMDCM_ProyectoIPS.RelacionAccionConnectAction(this);
						this.relacionAccionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relacionAccionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSToolboxHelper.RelacionFinFilterString))
				{
					if (this.relacionFinConnectAction == null)
					{
						this.relacionFinConnectAction = new global::UPM_IPS.RDMDCM_ProyectoIPS.RelacionFinConnectAction(this);
						this.relacionFinConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relacionFinConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.relacionAccionConnectAction != null)
					{
						this.relacionAccionConnectAction.Dispose();
						this.relacionAccionConnectAction = null;
					}
					if(this.relacionFinConnectAction != null)
					{
						this.relacionFinConnectAction.Dispose();
						this.relacionFinConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// RDMDCM_ProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xc75f8b19, 0xd391, 0x4ed0, 0x85, 0x84, 0xa1, 0x4b, 0x0b, 0x65, 0x76, 0x2f);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RDMDCM_ProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RDMDCM_ProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.RDMDCM_ProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaPrincipal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaSecundaria), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.Menu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.Boton), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenuReferencesVentana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.BotonReferencesVentana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.BotonReferencesEstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenuReferencesEstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaPrincipal)
				{
					parentElement = GetParentForVentanaPrincipal((global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaPrincipal)childElement);
				} else
				if(childElement is global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaSecundaria)
				{
					parentElement = GetParentForVentanaSecundaria((global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaSecundaria)childElement);
				} else
				if(childElement is global::UPM_IPS.RDMDCM_ProyectoIPS.Menu)
				{
					parentElement = GetParentForMenu((global::UPM_IPS.RDMDCM_ProyectoIPS.Menu)childElement);
				} else
				if(childElement is global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenu)
				{
					parentElement = GetParentForItemMenu((global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenu)childElement);
				} else
				if(childElement is global::UPM_IPS.RDMDCM_ProyectoIPS.Boton)
				{
					parentElement = GetParentForBoton((global::UPM_IPS.RDMDCM_ProyectoIPS.Boton)childElement);
				} else
				if(childElement is global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin)
				{
					parentElement = GetParentForEstadoFin((global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz GetParentForVentanaPrincipal( global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz GetParentForVentanaSecundaria( global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz GetParentForMenu( global::UPM_IPS.RDMDCM_ProyectoIPS.Menu root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana root2 = root.Ventana;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz result = root2.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz GetParentForItemMenu( global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenu root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RDMDCM_ProyectoIPS.Menu root2 = root.Menu;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana root4 = root2.Ventana;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz result = root4.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz GetParentForBoton( global::UPM_IPS.RDMDCM_ProyectoIPS.Boton root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana root2 = root.Ventana;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz result = root2.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz GetParentForEstadoFin( global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RDMDCM_ProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.Menu), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.RDMDCM_ProyectoIPS.Ventana.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaPrincipal.FindMetaforaVentanaPrincipalDecorator("nombreVentana");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaPrincipal.DomainClassId);
					}
					decorator = global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaVentanaSecundaria.FindMetaforaVentanaSecundariaDecorator("nombreVentana2");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaSecundaria.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.RDMDCM_ProyectoIPS.Menu.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaMenu.FindMetaforaMenuDecorator("nombreMenu");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.RDMDCM_ProyectoIPS.Menu.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.RDMDCM_ProyectoIPS.MetaforaEstadoFin.FindMetaforaEstadoFinDecorator("nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.RDMDCM_ProyectoIPS.EstadoFin.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenuReferencesVentana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.BotonReferencesVentana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.BotonReferencesEstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ItemMenuReferencesEstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
