//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.RDMDCM_ProyectoIPS
{
	/// <summary>
	/// DomainModel RDMDCM_ProyectoIPSDomainModel
	/// Description for UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel), "UPM_IPS.RDMDCM_ProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel), "UPM_IPS.RDMDCM_ProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("46aebfe7-52d3-499a-87a1-1679f1f83770")]
	public partial class RDMDCM_ProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// RDMDCM_ProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x46aebfe7, 0x52d3, 0x499a, 0x87, 0xa1, 0x16, 0x79, 0xf1, 0xf8, 0x37, 0x70);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public RDMDCM_ProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Ventana),
				typeof(VentanaSecundaria),
				typeof(Boton),
				typeof(Menu),
				typeof(ItemMenu),
				typeof(EstadoFin),
				typeof(VentanaPrincipal),
				typeof(TapizHasVentanas),
				typeof(VentanaHasMenus),
				typeof(MenuHasItemMenus),
				typeof(VentanaHasBotons),
				typeof(TapizHasEstadoFinned),
				typeof(ItemMenuReferencesVentana),
				typeof(BotonReferencesVentana),
				typeof(ItemMenuReferencesEstadoFin),
				typeof(BotonReferencesEstadoFin),
				typeof(RDMDCM_ProyectoIPSDiagram),
				typeof(MetaforaRelacionAccion),
				typeof(MetaforaRelacionFin),
				typeof(MetaforaVentanaPrincipal),
				typeof(MetaforaVentanaSecundaria),
				typeof(MetaforaMenu),
				typeof(MetaforaItemMenu),
				typeof(MetaforaBoton),
				typeof(MetaforaEstadoFin),
				typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Tapiz), "solucionDiagrama", Tapiz.solucionDiagramaDomainPropertyId, typeof(Tapiz.solucionDiagramaPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "nombre", Ventana.nombreDomainPropertyId, typeof(Ventana.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "ancho", Ventana.anchoDomainPropertyId, typeof(Ventana.anchoPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "alto", Ventana.altoDomainPropertyId, typeof(Ventana.altoPropertyHandler)),
				new DomainMemberInfo(typeof(VentanaSecundaria), "modal", VentanaSecundaria.modalDomainPropertyId, typeof(VentanaSecundaria.modalPropertyHandler)),
				new DomainMemberInfo(typeof(Boton), "nombre", Boton.nombreDomainPropertyId, typeof(Boton.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Menu), "nombre", Menu.nombreDomainPropertyId, typeof(Menu.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(ItemMenu), "nombre", ItemMenu.nombreDomainPropertyId, typeof(ItemMenu.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstadoFin), "nombre", EstadoFin.nombreDomainPropertyId, typeof(EstadoFin.nombrePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizHasVentanas), "Tapiz", TapizHasVentanas.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasVentanas), "Ventana", TapizHasVentanas.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasMenus), "Ventana", VentanaHasMenus.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasMenus), "Menu", VentanaHasMenus.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(MenuHasItemMenus), "Menu", MenuHasItemMenus.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(MenuHasItemMenus), "ItemMenu", MenuHasItemMenus.ItemMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasBotons), "Ventana", VentanaHasBotons.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasBotons), "Boton", VentanaHasBotons.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstadoFinned), "Tapiz", TapizHasEstadoFinned.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstadoFinned), "EstadoFin", TapizHasEstadoFinned.EstadoFinDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemMenuReferencesVentana), "ItemMenu", ItemMenuReferencesVentana.ItemMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemMenuReferencesVentana), "Ventana", ItemMenuReferencesVentana.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(BotonReferencesVentana), "Boton", BotonReferencesVentana.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(BotonReferencesVentana), "VentanaReferenciada", BotonReferencesVentana.VentanaReferenciadaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemMenuReferencesEstadoFin), "ItemMenu", ItemMenuReferencesEstadoFin.ItemMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemMenuReferencesEstadoFin), "EstadoFin", ItemMenuReferencesEstadoFin.EstadoFinDomainRoleId),
				new DomainRolePlayerInfo(typeof(BotonReferencesEstadoFin), "Boton", BotonReferencesEstadoFin.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(BotonReferencesEstadoFin), "EstadoFin", BotonReferencesEstadoFin.EstadoFinDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(17);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(VentanaSecundaria), 1);
				createElementMap.Add(typeof(Boton), 2);
				createElementMap.Add(typeof(Menu), 3);
				createElementMap.Add(typeof(ItemMenu), 4);
				createElementMap.Add(typeof(EstadoFin), 5);
				createElementMap.Add(typeof(VentanaPrincipal), 6);
				createElementMap.Add(typeof(RDMDCM_ProyectoIPSDiagram), 7);
				createElementMap.Add(typeof(MetaforaRelacionAccion), 8);
				createElementMap.Add(typeof(MetaforaRelacionFin), 9);
				createElementMap.Add(typeof(MetaforaVentanaPrincipal), 10);
				createElementMap.Add(typeof(MetaforaVentanaSecundaria), 11);
				createElementMap.Add(typeof(MetaforaMenu), 12);
				createElementMap.Add(typeof(MetaforaItemMenu), 13);
				createElementMap.Add(typeof(MetaforaBoton), 14);
				createElementMap.Add(typeof(MetaforaEstadoFin), 15);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new VentanaSecundaria(partition, propertyAssignments);
				case 2: return new Boton(partition, propertyAssignments);
				case 3: return new Menu(partition, propertyAssignments);
				case 4: return new ItemMenu(partition, propertyAssignments);
				case 5: return new EstadoFin(partition, propertyAssignments);
				case 6: return new VentanaPrincipal(partition, propertyAssignments);
				case 7: return new RDMDCM_ProyectoIPSDiagram(partition, propertyAssignments);
				case 8: return new MetaforaRelacionAccion(partition, propertyAssignments);
				case 9: return new MetaforaRelacionFin(partition, propertyAssignments);
				case 10: return new MetaforaVentanaPrincipal(partition, propertyAssignments);
				case 11: return new MetaforaVentanaSecundaria(partition, propertyAssignments);
				case 12: return new MetaforaMenu(partition, propertyAssignments);
				case 13: return new MetaforaItemMenu(partition, propertyAssignments);
				case 14: return new MetaforaBoton(partition, propertyAssignments);
				case 15: return new MetaforaEstadoFin(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementLinkMap.Add(typeof(TapizHasVentanas), 0);
				createElementLinkMap.Add(typeof(VentanaHasMenus), 1);
				createElementLinkMap.Add(typeof(MenuHasItemMenus), 2);
				createElementLinkMap.Add(typeof(VentanaHasBotons), 3);
				createElementLinkMap.Add(typeof(TapizHasEstadoFinned), 4);
				createElementLinkMap.Add(typeof(ItemMenuReferencesVentana), 5);
				createElementLinkMap.Add(typeof(BotonReferencesVentana), 6);
				createElementLinkMap.Add(typeof(ItemMenuReferencesEstadoFin), 7);
				createElementLinkMap.Add(typeof(BotonReferencesEstadoFin), 8);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.RDMDCM_ProyectoIPS.RDMDCM_ProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizHasVentanas(partition, roleAssignments, propertyAssignments);
				case 1: return new VentanaHasMenus(partition, roleAssignments, propertyAssignments);
				case 2: return new MenuHasItemMenus(partition, roleAssignments, propertyAssignments);
				case 3: return new VentanaHasBotons(partition, roleAssignments, propertyAssignments);
				case 4: return new TapizHasEstadoFinned(partition, roleAssignments, propertyAssignments);
				case 5: return new ItemMenuReferencesVentana(partition, roleAssignments, propertyAssignments);
				case 6: return new BotonReferencesVentana(partition, roleAssignments, propertyAssignments);
				case 7: return new ItemMenuReferencesEstadoFin(partition, roleAssignments, propertyAssignments);
				case 8: return new BotonReferencesEstadoFin(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.RDMDCM_ProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return RDMDCM_ProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (RDMDCM_ProyectoIPSDomainModel.resourceManager == null)
				{
					RDMDCM_ProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(RDMDCM_ProyectoIPSDomainModel).Assembly);
				}
				return RDMDCM_ProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return RDMDCM_ProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return RDMDCM_ProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (RDMDCM_ProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new RDMDCM_ProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					RDMDCM_ProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return RDMDCM_ProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (RDMDCM_ProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new RDMDCM_ProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					RDMDCM_ProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return RDMDCM_ProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.RDMDCM_ProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RDMDCM_ProyectoIPSDeleteClosure : RDMDCM_ProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RDMDCM_ProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RDMDCM_ProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public RDMDCM_ProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.RDMDCM_ProyectoIPS.TapizHasVentanas.VentanaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaHasMenus.MenuDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RDMDCM_ProyectoIPS.MenuHasItemMenus.ItemMenuDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RDMDCM_ProyectoIPS.VentanaHasBotons.BotonDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RDMDCM_ProyectoIPS.TapizHasEstadoFinned.EstadoFinDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RDMDCM_ProyectoIPSCopyClosure : RDMDCM_ProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RDMDCM_ProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RDMDCM_ProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RDMDCM_ProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

