//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.RDMDCM_ProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "RDMDCM_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"RDMDCM_ProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RDMDCM_ProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RDMDCM_ProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RDMDCM_ProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RDMDCM_ProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRDMDCM_ProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RDMDCM_ProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string RDMDCM_ProyectoIPSPackageId = "524c9a59-6083-4d02-b9f9-4827f856db75";
		
		// Editor factory identifier
		public const string RDMDCM_ProyectoIPSEditorFactoryId = "298e28e6-2777-47a8-8fff-6187462ab2aa";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RDMDCM_ProyectoIPSModelExplorerToolWindowId = "e24d0016-f6af-43ac-802a-e067a713dda4";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.RDMDCM_ProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RDMDCM_ProyectoIPSCommandSetId = "c192ac9c-642a-4c0a-b80f-4edf32716da0";
	}
}